services:
  cups-airprint:
    container_name: cups-airprint
    image: cups-airprint:latest
    build: .
    restart: always
    network_mode: host
    environment:
      DEBUG: 1
      CUPSADMIN: "admin"
      CUPSPASSWORD: "admin"
      CUPSMODE: "cups"
    volumes:
      - "/volume1/onedrive/smarthome/data/cups/services:/services"
      - "/volume1/onedrive/smarthome/data/cups/config:/config"    
      - "/etc/localtime:/etc/localtime:ro"
    dns:
      - 10.79.10.1
    env_file:
      - .env

